### NumPy Arrays

In [1]:
# Generate a numpy array of size 4 by 5.

# [1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15], [16,17,18,19,20]

# Use index slicing and show how to get the subarray consisting of 
# the last two rows and the third and fourth columns.

# Show how to create a one-dimensional array that sums the columns.

In [4]:
import numpy as np

a = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15], [16,17,18,19,20]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [12]:
subarray = a[2:,3:]  # a[rows, columns]
subarray

array([[14, 15],
       [19, 20]])

In [24]:
sum_of_columns = np.array([sum(a[:,0]),sum(a[:,1]),sum(a[:,2]),sum(a[:,3]),sum(a[:,4])])
sum_of_columns

array([34, 38, 42, 46, 50])